-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 00:43:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rasbet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rasbet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rasbet` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema rasbet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rasbet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rasbet` DEFAULT CHARACTER SET latin1 ;
USE `rasbet` ;

-- -----------------------------------------------------
-- Table `rasbet`.`Odds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Odds` (
  `idOdds` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(128) NULL,
  `odd` FLOAT NULL,
  `estado` INT NULL DEFAULT 0,
  PRIMARY KEY (`idOdds`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rasbet`.`Moeda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Moeda` (
  `idMoeda` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `saldo` VARCHAR(45) NULL,
  PRIMARY KEY (`idMoeda`))
ENGINE = InnoDB;

USE `rasbet` ;

-- -----------------------------------------------------
-- Table `rasbet`.`Apostador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Apostador` (
  `idApostador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `dataN` DATE NULL DEFAULT NULL,
  `nCC` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idApostador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Aposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Aposta` (
  `idAposta` INT NOT NULL AUTO_INCREMENT,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `estado` INT NULL DEFAULT NULL,
  `odd` FLOAT NULL DEFAULT NULL,
  `Apostador_idApostador` INT NOT NULL,
  `Moeda_idMoeda` INT NOT NULL,
  PRIMARY KEY (`idAposta`),
  INDEX `fk_Aposta_Apostador_idx` (`Apostador_idApostador` ASC),
  INDEX `fk_Aposta_Moeda1_idx` (`Moeda_idMoeda` ASC),
  CONSTRAINT `fk_Aposta_Apostador`
    FOREIGN KEY (`Apostador_idApostador`)
    REFERENCES `rasbet`.`Apostador` (`idApostador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aposta_Moeda1`
    FOREIGN KEY (`Moeda_idMoeda`)
    REFERENCES `rasbet`.`Moeda` (`idMoeda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Jogo` (
  `idJogo` VARCHAR(64) NOT NULL,
  `data_inicio` DATETIME NULL DEFAULT NULL,
  `estado` INT NULL DEFAULT NULL,
  `resultado` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`idJogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Aposta_has_Jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Aposta_has_Jogo` (
  `Aposta_idAposta` INT NOT NULL,
  `Jogo_idJogo` VARCHAR(64) NOT NULL,
  `Odds_idOdds` INT NOT NULL,
  PRIMARY KEY (`Aposta_idAposta`, `Jogo_idJogo`,`Odds_idOdds`),
  INDEX `fk_Aposta_has_Jogo_Jogo1_idx` (`Jogo_idJogo` ASC),
  INDEX `fk_Aposta_has_Jogo_Aposta1_idx` (`Aposta_idAposta` ASC),
  INDEX `fk_Aposta_has_Jogo_Odds1_idx` (`Odds_idOdds` ASC),
  CONSTRAINT `fk_Aposta_has_Jogo_Aposta1`
    FOREIGN KEY (`Aposta_idAposta`)
    REFERENCES `rasbet`.`Aposta` (`idAposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aposta_has_Jogo_Jogo1`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `rasbet`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aposta_has_Jogo_Odds1`
    FOREIGN KEY (`Odds_idOdds`)
    REFERENCES `rasbet`.`Odds` (`idOdds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Equipa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Equipa` (
  `nome` VARCHAR(128) NOT NULL,
  `desporto` VARCHAR(64) NULL DEFAULT NULL,
  `pais` VARCHAR(64) NULL DEFAULT NULL,
  `liga` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Movimento` (
  `idMovimento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(64) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `saldo` FLOAT NULL DEFAULT NULL,
  `data` DATETIME NULL DEFAULT NULL,
  `Apostador_idApostador` INT NOT NULL,
  `Moeda_idMoeda` INT NOT NULL,
  PRIMARY KEY (`idMovimento`),
  INDEX `fk_Movimento_Apostador1_idx` (`Apostador_idApostador` ASC),
  INDEX `fk_Movimento_Moeda1_idx` (`Moeda_idMoeda` ASC),
  CONSTRAINT `fk_Movimento_Apostador1`
    FOREIGN KEY (`Apostador_idApostador`)
    REFERENCES `rasbet`.`Apostador` (`idApostador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimento_Moeda1`
    FOREIGN KEY (`Moeda_idMoeda`)
    REFERENCES `rasbet`.`Moeda` (`idMoeda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Jogo_has_Equipa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Jogo_has_Equipa` (
  `Jogo_idJogo` VARCHAR(64) NOT NULL,
  `Equipa_nome` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Jogo_idJogo`, `Equipa_nome`),
  INDEX `fk_Jogo_has_Equipa_Equipa1_idx` (`Equipa_nome` ASC),
  INDEX `fk_Jogo_has_Equipa_Jogo1_idx` (`Jogo_idJogo` ASC),
  CONSTRAINT `fk_Jogo_has_Equipa_Jogo1`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `rasbet`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_Equipa_Equipa1`
    FOREIGN KEY (`Equipa_nome`)
    REFERENCES `rasbet`.`Equipa` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `rasbet`.`Apostador_has_Moeda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Apostador_has_Moeda` (
  `Apostador_idApostador` INT NOT NULL,
  `Moeda_idMoeda` INT NOT NULL,
  PRIMARY KEY (`Apostador_idApostador`, `Moeda_idMoeda`),
  INDEX `fk_Apostador_has_Moeda_Moeda1_idx` (`Moeda_idMoeda` ASC),
  INDEX `fk_Apostador_has_Moeda_Apostador1_idx` (`Apostador_idApostador` ASC),
  CONSTRAINT `fk_Apostador_has_Moeda_Apostador1`
    FOREIGN KEY (`Apostador_idApostador`)
    REFERENCES `rasbet`.`Apostador` (`idApostador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apostador_has_Moeda_Moeda1`
    FOREIGN KEY (`Moeda_idMoeda`)
    REFERENCES `rasbet`.`Moeda` (`idMoeda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rasbet`.`Jogo_has_Odds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rasbet`.`Jogo_has_Odds` (
  `Jogo_idJogo` VARCHAR(64) NOT NULL,
  `Odds_idOdds` INT NOT NULL,
  PRIMARY KEY (`Jogo_idJogo`, `Odds_idOdds`),
  INDEX `fk_Jogo_has_Odds_Odds1_idx` (`Odds_idOdds` ASC),
  INDEX `fk_Jogo_has_Odds_Jogo1_idx` (`Jogo_idJogo` ASC),
  CONSTRAINT `fk_Jogo_has_Odds_Jogo1`
    FOREIGN KEY (`Jogo_idJogo`)
    REFERENCES `rasbet`.`Jogo` (`idJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogo_has_Odds_Odds1`
    FOREIGN KEY (`Odds_idOdds`)
    REFERENCES `rasbet`.`Odds` (`idOdds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
